apiVersion: v1
entries:
  joget:
  - annotations:
      catalog.cattle.io/display-name: Joget DX
      catalog.cattle.io/permits-os: windows,linux
      category: PaaS
    apiVersion: v2
    appVersion: 8.0.11
    created: "2024-03-14T11:34:39.574737104+08:00"
    description: Open source no-code/low-code application platform
    digest: 5f198fdc3a0f310154e430dd312ccbf4f367511054e13d2c3c6d19b51775198d
    home: https://www.joget.com
    icon: https://www.joget.org/wp-content/uploads/2023/07/Joget_logo_Vertical_Green_Symbol.png
    keywords:
    - low-code
    - no-code
    - PaaS
    kubeVersion: '>=1.18-0'
    name: joget
    type: application
    urls:
    - joget-1.0.0.tgz
    version: 1.0.0
generated: "2024-03-14T11:34:39.573780174+08:00"
