# This is a basic workflow to help you get started with Actions

name: Run partner-chart-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: jogetameerizwan/partner-charts
          ref: main-source
      # Runs a single command using the runners shell
      - name: Pull CI script, run script to generate new asset files and commit changes
        run: |
          ./scripts/pull-scripts
          echo "Configuring git"
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          PACKAGE=joget/joget ./bin/partner-charts-ci update --commit
          echo "Package Joget updated"
      - name: Push committed changes
        run: |
          echo "Pushing updated changes"
          git status
          git log -1 --stat
          git push origin main

      # Runs a set of commands using the runners shell
